version: '3'
services:
  main_app:
    build: 
      context: .
    volumes:
      - .:/main_app
    ports:
      - 3005:3005
    image: products_main:1.0
    container_name: products_main
    command: pnpm serve --host 0.0.0.0
